# Generated by Django 4.2.7 on 2025-11-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Region name, e.g. 'Ilocos Region'", max_length=100
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        help_text="Province name, e.g. 'Ilocos Norte'", max_length=100
                    ),
                ),
                (
                    "city_municipality",
                    models.CharField(
                        help_text="City/Municipality name, e.g. 'Laoag City'",
                        max_length=100,
                    ),
                ),
                (
                    "barangay",
                    models.CharField(
                        help_text="Barangay name, e.g. 'Barangay 1'", max_length=100
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ChatbotKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Help"),
                            ("ordering", "Ordering Process"),
                            ("products", "Products & Inventory"),
                            ("account", "Account Management"),
                            ("shipping", "Shipping & Delivery"),
                            ("payment", "Payment Methods"),
                            ("customization", "Product Customization"),
                            ("returns", "Returns & Refunds"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        help_text="Comma-separated keywords that trigger this response"
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pic/CustomerProfilePic/",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("NCR", "National Capital Region"),
                            ("CAR", "Cordillera Administrative Region"),
                            ("R1", "Ilocos Region"),
                            ("R2", "Cagayan Valley"),
                            ("R3", "Central Luzon"),
                            ("R4A", "CALABARZON"),
                            ("R4B", "MIMAROPA"),
                            ("R5", "Bicol Region"),
                            ("R6", "Western Visayas"),
                            ("R7", "Central Visayas"),
                            ("R8", "Eastern Visayas"),
                            ("R9", "Zamboanga Peninsula"),
                            ("R10", "Northern Mindanao"),
                            ("R11", "Davao Region"),
                            ("R12", "SOCCSKSARGEN"),
                            ("R13", "Caraga"),
                            (
                                "BARMM",
                                "Bangsamoro Autonomous Region in Muslim Mindanao",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("citymun", models.CharField(blank=True, max_length=100, null=True)),
                ("barangay", models.CharField(blank=True, max_length=100, null=True)),
                ("street_address", models.CharField(max_length=100)),
                ("postal_code", models.PositiveIntegerField()),
                (
                    "mobile",
                    models.CharField(
                        help_text="Enter 10 digits, e.g. '956 837 0169'", max_length=13
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomJerseyDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jersey_type", models.CharField(default="jersey", max_length=50)),
                ("collar_type", models.CharField(default="crew_neck", max_length=50)),
                (
                    "sleeve_type",
                    models.CharField(default="short_sleeve", max_length=50),
                ),
                ("design_scale", models.FloatField(default=1.0)),
                ("fabric_type", models.CharField(default="polyester", max_length=50)),
                ("is_3d_design", models.BooleanField(default=False)),
                (
                    "logo_position_3d",
                    models.JSONField(
                        default=dict, help_text="3D logo position coordinates"
                    ),
                ),
                (
                    "text_position_3d",
                    models.JSONField(
                        default=dict, help_text="3D text position coordinates"
                    ),
                ),
                ("primary_color", models.CharField(default="#000000", max_length=7)),
                ("secondary_color", models.CharField(default="#ffffff", max_length=7)),
                ("pattern", models.CharField(default="solid", max_length=50)),
                (
                    "front_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("back_name", models.CharField(blank=True, max_length=50, null=True)),
                ("back_number", models.CharField(blank=True, max_length=10, null=True)),
                ("text_color", models.CharField(default="#000000", max_length=7)),
                ("logo_placement", models.CharField(default="none", max_length=50)),
                (
                    "design_data",
                    models.JSONField(help_text="Complete design configuration as JSON"),
                ),
                (
                    "design_image",
                    models.ImageField(
                        blank=True,
                        help_text="Generated image of the custom jersey design",
                        null=True,
                        upload_to="custom_designs/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("feedback", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_image/"
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=40)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("XS", "Extra Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        default="M",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courier", models.CharField(max_length=50)),
                ("origin_region", models.CharField(max_length=50)),
                ("destination_region", models.CharField(max_length=50)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=4)),
                ("price_php", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Super Admin",
                "verbose_name_plural": "Super Admins",
            },
        ),
        migrations.CreateModel(
            name="SavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("NCR", "National Capital Region"),
                            ("CAR", "Cordillera Administrative Region"),
                            ("R1", "Ilocos Region"),
                            ("R2", "Cagayan Valley"),
                            ("R3", "Central Luzon"),
                            ("R4A", "CALABARZON"),
                            ("R4B", "MIMAROPA"),
                            ("R5", "Bicol Region"),
                            ("R6", "Western Visayas"),
                            ("R7", "Central Visayas"),
                            ("R8", "Eastern Visayas"),
                            ("R9", "Zamboanga Peninsula"),
                            ("R10", "Northern Mindanao"),
                            ("R11", "Davao Region"),
                            ("R12", "SOCCSKSARGEN"),
                            ("R13", "Caraga"),
                            (
                                "BARMM",
                                "Bangsamoro Autonomous Region in Muslim Mindanao",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("province", models.CharField(max_length=100)),
                ("citymun", models.CharField(max_length=100)),
                ("barangay", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=100)),
                ("postal_code", models.PositiveIntegerField()),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_addresses",
                        to="ecom.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the order was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the order was last updated"
                    ),
                ),
                ("email", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("mobile", models.CharField(max_length=20, null=True)),
                (
                    "order_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when order was placed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending - Awaiting Payment"),
                            ("Processing", "Processing - Payment Confirmed"),
                            ("Order Confirmed", "Order Confirmed - In Production"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Delivered", "Delivered"),
                            (
                                "Cancellation Requested",
                                "Waiting for approval of Cancellation",
                            ),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        help_text="Current status of the order",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the status was last changed",
                        null=True,
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(
                        blank=True, help_text="Estimated delivery date", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the order",
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("paypal", "PayPal"),
                            ("gcash", "GCash"),
                        ],
                        default="cod",
                        help_text="Payment method for the order",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="PayPal or GCash transaction ID for paid orders",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "order_ref",
                    models.CharField(
                        blank=True,
                        help_text="Unique short order reference ID",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Delivery fee for this order",
                        max_digits=10,
                    ),
                ),
                (
                    "delivery_proof_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Customer uploaded proof of delivery photo",
                        null=True,
                        upload_to="delivery_proof/",
                    ),
                ),
                (
                    "customer_received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customer confirmed receipt with photo proof",
                        null=True,
                    ),
                ),
                (
                    "cancellation_status",
                    models.CharField(
                        choices=[
                            ("none", "No Cancellation Request"),
                            ("requested", "Cancellation Requested"),
                            ("approved", "Cancellation Approved"),
                            ("rejected", "Cancellation Rejected"),
                        ],
                        default="none",
                        help_text="Status of cancellation request",
                        max_length=20,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by customer for cancellation",
                        null=True,
                    ),
                ),
                (
                    "cancellation_requested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When cancellation was requested",
                        null=True,
                    ),
                ),
                (
                    "cancellation_approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When cancellation was approved/rejected",
                        null=True,
                    ),
                ),
                (
                    "cancellation_admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes regarding the cancellation decision",
                        null=True,
                    ),
                ),
                (
                    "refund_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether refund has been processed for paid orders",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount refunded to customer",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "refund_processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When refund was processed", null=True
                    ),
                ),
                (
                    "cancellation_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Super Admin who approved/rejected the cancellation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cancellations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom.customer",
                    ),
                ),
                (
                    "refund_processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed the refund",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Small"),
                            ("XS", "Extra Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.orders"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
            },
        ),
        migrations.CreateModel(
            name="DeliveryStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("new_status", models.CharField(max_length=50)),
                (
                    "updated_by",
                    models.CharField(
                        help_text="Who updated the status (admin, system, external)",
                        max_length=100,
                    ),
                ),
                (
                    "update_method",
                    models.CharField(
                        help_text="How the status was updated (dashboard, magic_link, api)",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="ecom.orders",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryMagicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique token for the magic link",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this magic link expires"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_link",
                        to="ecom.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("XS", "Extra Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=5,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("is_pre_order", models.BooleanField(default=False)),
                (
                    "pre_order_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_production", "In Production"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom.customjerseydesign",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.orders"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "handover_status",
                    models.CharField(
                        choices=[
                            ("bot", "Bot Handling"),
                            ("requested", "Admin Help Requested"),
                            ("admin", "Admin Handling"),
                            ("resolved", "Resolved"),
                        ],
                        default="bot",
                        max_length=20,
                    ),
                ),
                ("handover_requested_at", models.DateTimeField(blank=True, null=True)),
                ("admin_joined_at", models.DateTimeField(blank=True, null=True)),
                ("handover_reason", models.TextField(blank=True, null=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("bot", "Bot Response"),
                            ("admin", "Admin Response"),
                            ("system", "System Message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ecom.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BulkOrderOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("status_update", "Status Update"),
                            ("bulk_progress", "Bulk Progress"),
                            ("export", "Export Orders"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        help_text="Operation parameters (status, filters, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "orders_affected",
                    models.ManyToManyField(
                        related_name="bulk_operations", to="ecom.orders"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "product")},
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "product")},
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("XS", "Extra Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=5,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecom.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "product", "size")},
            },
        ),
    ]
