# Generated by Django 4.2.7 on 2025-10-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0054_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
