# Generated by Django 4.2.7 on 2025-10-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0055_remove_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.product'),
        ),
    ]
