# Generated by Django 4.2.7 on 2025-10-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0056_inventoryitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomJerseyDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_type', models.CharField(default='standard', max_length=50)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('pattern', models.CharField(default='solid', max_length=50)),
                ('front_number', models.CharField(blank=True, max_length=10, null=True)),
                ('back_name', models.CharField(blank=True, max_length=50, null=True)),
                ('back_number', models.CharField(blank=True, max_length=10, null=True)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('logo_placement', models.CharField(default='none', max_length=50)),
                ('design_data', models.JSONField(help_text='Complete design configuration as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('XS', 'Extra Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_pre_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.customjerseydesign')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.orders')),
            ],
        ),
    ]
