# Generated by Django 4.2.7 on 2025-10-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0057_customjerseydesign_customorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderitem',
            name='pre_order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
