# Generated by Django 4.2.7 on 2025-10-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0058_customorderitem_pre_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customjerseydesign',
            name='design_image',
            field=models.ImageField(blank=True, help_text='Generated image of the custom jersey design', null=True, upload_to='custom_designs/'),
        ),
    ]
