# Generated by Django 4.2.7 on 2025-10-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0060_reporttemplate_scheduledreport_salesreportdata_and_more'),
    ]

    operations = [
        # Drop all report-related tables
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_scheduledreport;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_reportaccess;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_generatedreport;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_reporttemplate;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_salesreportdata;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_customerreportdata;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_inventoryreportdata;"),
        migrations.RunSQL("DROP TABLE IF EXISTS ecom_productreportdata;"),
    ]
