# Generated by Django 4.2.7 on 2025-10-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0061_auto_20251027_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReportData',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='template',
        ),
        migrations.DeleteModel(
            name='InventoryReportData',
        ),
        migrations.AlterUniqueTogether(
            name='productreportdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productreportdata',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='reportaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='SalesReportData',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='template',
        ),
        migrations.DeleteModel(
            name='GeneratedReport',
        ),
        migrations.DeleteModel(
            name='ProductReportData',
        ),
        migrations.DeleteModel(
            name='ReportAccess',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.DeleteModel(
            name='ScheduledReport',
        ),
    ]
