# Generated by Django 5.1.6 on 2025-10-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0061_delete_customerreportdata_and_more'),
        ('ecom', '0062_delete_customerreportdata_and_more'),
    ]

    operations = [
    ]
