# Generated by Django 4.2.7 on 2025-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0072_emailverification_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReportData',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='template',
        ),
        migrations.DeleteModel(
            name='InventoryReportData',
        ),
        migrations.AlterUniqueTogether(
            name='productreportdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productreportdata',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='reportaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='SalesReportData',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='template',
        ),
        migrations.AlterField(
            model_name='customjerseydesign',
            name='collar_type',
            field=models.CharField(default='crew_neck', max_length=50),
        ),
        migrations.AlterField(
            model_name='customjerseydesign',
            name='jersey_type',
            field=models.CharField(default='jersey', max_length=50),
        ),
        migrations.DeleteModel(
            name='GeneratedReport',
        ),
        migrations.DeleteModel(
            name='ProductReportData',
        ),
        migrations.DeleteModel(
            name='ReportAccess',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.DeleteModel(
            name='ScheduledReport',
        ),
    ]
