# Generated by Django 4.2.7 on 2025-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0072_emailverification_new'),
    ]

    # 0061 already dropped these tables via raw SQL with IF EXISTS.
    # Convert destructive ops to state-only so this migration is idempotent
    # across environments where tables may already be gone.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='CustomerReportData')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('generatedreport', 'generated_by')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('generatedreport', 'template')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='InventoryReportData')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.AlterUniqueTogether(name='productreportdata', unique_together=None)],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('productreportdata', 'product')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.AlterUniqueTogether(name='reportaccess', unique_together=None)],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('reportaccess', 'user')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('reporttemplate', 'created_by')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='SalesReportData')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('scheduledreport', 'created_by')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField('scheduledreport', 'template')],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='customjerseydesign',
            name='collar_type',
            field=models.CharField(default='crew_neck', max_length=50),
        ),
        migrations.AlterField(
            model_name='customjerseydesign',
            name='jersey_type',
            field=models.CharField(default='jersey', max_length=50),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='GeneratedReport')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='ProductReportData')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='ReportAccess')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='ReportTemplate')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='ScheduledReport')],
            database_operations=[],
        ),
    ]
