# Generated by Django 4.2.7 on 2025-10-29 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0073_delete_customerreportdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancellation_admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes regarding the cancellation decision', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancellation_approved_at',
            field=models.DateTimeField(blank=True, help_text='When cancellation was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancellation_approved_by',
            field=models.ForeignKey(blank=True, help_text='Super Admin who approved/rejected the cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided by customer for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, help_text='When cancellation was requested', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancellation_status',
            field=models.CharField(choices=[('none', 'No Cancellation Request'), ('requested', 'Cancellation Requested'), ('approved', 'Cancellation Approved'), ('rejected', 'Cancellation Rejected')], default='none', help_text='Status of cancellation request', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded to customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_processed',
            field=models.BooleanField(default=False, help_text='Whether refund has been processed for paid orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('paypal', 'PayPal'), ('gcash', 'GCash')], default='cod', help_text='Payment method for the order', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending - Awaiting Payment'), ('Processing', 'Processing - Payment Confirmed'), ('Order Confirmed', 'Order Confirmed - In Production'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Cancellation Requested', 'Waiting for approval of Cancellation')], default='Pending', help_text='Current status of the order', max_length=50, null=True),
        ),
    ]
