# Generated by Django 4.2.7 on 2025-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0074_orders_cancellation_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='PayPal or GCash transaction ID for paid orders', max_length=100, null=True),
        ),
    ]
