"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')
STATIC_DIR=os.path.join(BASE_DIR,'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='#vw(03o=(9kbvg!&2d5i!2$_58x@_-3l4wujpow6(ym37jxnza')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '147.185.221.29',
    '147.185.221.29:64472',
    'worksteamwear.playit.pub',
    '147.185.221.16:24531',
    '147.185.221.16',
    '147.185.221.212',
    '147.185.221.20',
    '147.185.221.20:4104',
    'worksteamwear.shop',
    'www.worksteamwear.shop',
    '47.129.161.196',
    '*',
]

# Base URL for generating absolute links in emails (optional override)
PUBLIC_BASE_URL = config('PUBLIC_BASE_URL', default='')

# Trust proxy headers so request.build_absolute_uri uses correct host/scheme
USE_X_FORWARDED_HOST = True

# Allow CSRF on common hosted domains (adjust as needed)
CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'https://*.app.github.dev',
    'http://worksteamwear.shop',
    'https://worksteamwear.shop',
    'http://www.worksteamwear.shop',
    'https://www.worksteamwear.shop',
    'https://ecom.worksteamwear.shop',
    'http://ecom.worksteamwear.shop',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'ecom',
    'widget_tweaks',
    'social_django',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecom.views.order_counts',
                'ecom.context_processors.superadmin_context',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# If DATABASE_URL is provided, use it (e.g., DigitalOcean Managed PostgreSQL)
DATABASE_URL = config('DATABASE_URL', default='')
if DATABASE_URL:
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=False)


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS=[STATIC_DIR,]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Serve compressed static files in production via WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL='/afterlogin'

# Add LOGIN_URL to fix redirect to login page URL
LOGIN_URL = '/customerlogin'

# Redirect to customer login after logout

# Logout redirect URL
LOGOUT_REDIRECT_URL = '/customerlogin'

# Authentication backends (add Google OAuth)
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Social Auth: Google OAuth2
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='')
# Ensure Google provides required user info and stable account selection
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['openid', 'email', 'profile']
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account',
    'access_type': 'offline'
}
# Explicit login URL for social auth error redirects
SOCIAL_AUTH_LOGIN_URL = '/customerlogin'
# Redirect settings
SOCIAL_AUTH_LOGIN_REDIRECT_URL = LOGIN_REDIRECT_URL
SOCIAL_AUTH_LOGIN_ERROR_URL = '/customerlogin'
# Treat HTTP as OK for localhost; set True behind HTTPS proxies
SOCIAL_AUTH_REDIRECT_IS_HTTPS = config('SOCIAL_AUTH_REDIRECT_IS_HTTPS', default=False, cast=bool)

# Force a stable callback during local development to avoid host mismatch.
# Override via env var in production.
SOCIAL_AUTH_REDIRECT_URI = config(
    'SOCIAL_AUTH_REDIRECT_URI',
    default='http://localhost:8000/oauth/complete/google-oauth2/'
)

# Raise exceptions from social-auth during development to see exact failure causes
if DEBUG:
    SOCIAL_AUTH_RAISE_EXCEPTIONS = True
    # Explicitly set cookie samesite for clarity; default is 'Lax' in Django
    SESSION_COOKIE_SAMESITE = 'Lax'

# Optional: add basic debug logging for social auth to aid troubleshooting
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'social': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Use default pipeline with an extra step to activate social users and ensure Customer profile
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'ecom.social_pipeline.ensure_active_customer',
)

#for contact us give your gmail id and password
# Email configuration - Use SMTP for actual email sending
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='mersyeon123@gmail.com') # this email will be used to send emails
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='your-app-password') # Gmail App Password (NOT regular password)

# For development testing only - uncomment the line below to use console backend
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# now sign in with your host gmail account in your browser
# open following link and turn it ON
# https://myaccount.google.com/lesssecureapps
# otherwise you will get SMTPAuthenticationError at /contactus
# this process is required because google blocks apps authentication by default

# Default from email for all outgoing emails
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER', default='mersyeon123@gmail.com')

EMAIL_RECEIVING_USER = [config('EMAIL_RECEIVING_USER', default='merss0103@gmail.com')] # email on which you will receive messages sent from website

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PayPal API Credentials
PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='AbktyGNl4UcmLDfE0d0Wm_YMY_bdcDmRO5dc3TEl7zR2XXACyUanC5vQr6lC4M4umP12sagxFbh1MP6J')
PAYPAL_SECRET_KEY = config('PAYPAL_SECRET_KEY', default='ELWqmuYmOjP4ssKV-II1KQuudeNpk4dngnQc_bpZD4L9Am9UFNrXTUgDl2GPq6OYa2YiSoFZSsLYygst')

# PSGC API Configuration
PSGC_API_BASE_URL = config('PSGC_API_BASE_URL', default='https://psgc.gitlab.io/api')

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}
